added a message to notice when 'git_integration_title' setting is missing.
"NoMethodError: undefined method `each' for nil:NilClass" in formatmetrics() #1209

https://github.com/DataDog/documentation/issues/1209