Updating the doc. to reflect that we do not support Elasticsearch8
Following the discovery of this FR:
* https://datadoghq.atlassian.net/jira/software/c/projects/FRAPMS/boards/608?modal=detail&selectedIssue=FRAPMS-3338&search=elast
Python with Elasticsearch8 leads to this error
```AttributeError: partially initialized module 'elasticsearch' has no attribute 'transport' (most likely due to a circular import)```